// sveltekit/app/src/lib/motion/PageMotion.svelte
<script lang="ts">
  import { onMount, tick, type Snippet } from "svelte";
  import { gsap } from "./gsap";
  import {
    INTRO_DURATION,
    INTRO_RISE,
    INTRO_STAGGER,
    OUTRO_DRIFT,
    OUTRO_DURATION,
    OUTRO_STAGGER,
    motionReleased,
    prefersReducedMotion,
    type Phase,
  } from "./phases";
  import { getRouteTransition, type PageController } from "./route-transition";

  let { children }: { children: Snippet } = $props();

  // Read during initialization, while the layout's context is in scope.
  const { registerPage } = getRouteTransition();

  let root: HTMLElement;
  /**
   * Server rendering emits `initial`, so the pre-paint rule in app.css applies
   * from the first byte and no settled content is ever painted early.
   */
  let phase = $state<Phase>("initial");

  onMount(() => {
    // Every selector resolves inside this page, and revert() kills the tweens
    // this page created and restores the inline styles they wrote.
    const context = gsap.context(() => {}, root);

    let intro: gsap.core.Timeline | null = null;

    /**
     * Advance one phase, and wait for Svelte to write it to the DOM before the
     * next one is set. Two phases in one flush would leave anything watching
     * the attribute with only the last of them.
     */
    const setPhase = async (next: Phase) => {
      if (phase === next) return;
      phase = next;
      await tick();
    };

    /** Queried per call, so anything rendered since setup is included. */
    const targets = () => gsap.utils.toArray<HTMLElement>("[data-intro]", root);

    const runIntro = async () => {
      // An intro can start on DOM that already holds settled values, so the
      // previous timeline is killed and start values are written explicitly
      // rather than inferred by a `from` tween that trusts a fresh node.
      intro?.kill();
      intro = null;
      await setPhase("initial");

      // No travel when the reader asked for none, and none when the pre-paint
      // failsafe already put the content on screen: hiding it again to play an
      // intro would be worse than arriving settled.
      const instant = prefersReducedMotion() || motionReleased();
      const els = targets();
      context.add(() => {
        gsap.set(els, instant ? { autoAlpha: 1, y: 0 } : { autoAlpha: 0, y: INTRO_RISE });
      });

      await setPhase("intro");

      const settle = async () => {
        intro = null;
        // Settled is plain CSS, not a held timeline: drop every temporary
        // transform, visibility, and will-change this page wrote.
        context.add(() => {
          gsap.set(els, { clearProps: "all" });
        });
        await setPhase("settled");
      };

      if (instant) {
        // No travel, but the same phases and the same completion.
        await settle();
        return;
      }

      context.add(() => {
        intro = gsap
          .timeline({ onComplete: settle })
          .set(els, { willChange: "transform, opacity" })
          .to(els, {
            autoAlpha: 1,
            y: 0,
            duration: INTRO_DURATION,
            stagger: INTRO_STAGGER,
            ease: "power2.out",
          });
      });
    };

    const runOutro = () =>
      new Promise<void>((resolve) => {
        // The intro is not the inverse of the outro, so kill it and leave from
        // whatever is on screen rather than reversing it.
        intro?.kill();
        intro = null;

        // Queried at leave time so late-arriving content leaves with the page.
        const els = targets();

        let ended = false;
        const end = () => {
          if (ended) return;
          ended = true;
          // Still mounted and still laid out, just no longer interactive: the
          // `end` phase drives that from CSS, so nothing has to be cleaned up.
          void setPhase("end").then(resolve);
        };

        void setPhase("outro").then(() => {
          if (prefersReducedMotion()) {
            context.add(() => {
              gsap.set(els, { autoAlpha: 0 });
            });
            end();
            return;
          }
          context.add(() => {
            // onInterrupt as well as onComplete: a killed timeline never runs
            // its completion, and the router is waiting on this promise.
            gsap
              .timeline({ onComplete: end, onInterrupt: end })
              .set(els, { willChange: "transform, opacity" })
              .to(els, {
                autoAlpha: 0,
                y: -OUTRO_DRIFT,
                duration: OUTRO_DURATION,
                stagger: OUTRO_STAGGER,
                ease: "power2.in",
              });
          });
        });
      });

    const controller: PageController = {
      root,
      enter: () => void runIntro(),
      leave: runOutro,
    };
    const unregister = registerPage(controller);

    return () => {
      unregister();
      context.revert();
    };
  });
</script>

<div class="page-root" data-page data-phase={phase} bind:this={root}>
  {@render children()}
</div>

// react-router/app/app/motion/PageMotion.tsx
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { useRef, type ReactNode } from "react";
import { useLocation } from "react-router";
import {
  INTRO_RISE,
  OUTRO_DRIFT,
  motionReleased,
  nextStep,
  prefersReducedMotion,
  type Phase,
} from "./phases";
import { useRouteTransition, type PageController } from "./RouteTransition";

/** Intro: 0.4s of travel plus two 0.1s steps of stagger is the ~600ms asked for. */
const INTRO_DURATION = 0.4;
const INTRO_STAGGER = 0.1;
/** Outro: 0.34s plus two 0.03s steps is the ~350ms asked for. */
const OUTRO_DURATION = 0.34;
const OUTRO_STAGGER = 0.03;

/**
 * The lifecycle controller for one route's content.
 *
 * mount -> initial -> intro -> settled -> outro -> end -> unmount, with the
 * current phase written to `data-phase` on the wrapper it renders. Routes mark
 * what they animate with `data-intro` and otherwise stay plain modules.
 *
 * The setup depends on `pathname` with `revertOnUpdate`, the skill's default, so
 * a route the router reuses with new params runs its lifecycle again over DOM
 * that already holds settled values. That is also why every start value is an
 * explicit `set` rather than a `from` tween trusting a fresh node.
 */
export function PageMotion({ children }: { children: ReactNode }) {
  const root = useRef<HTMLDivElement>(null);
  const { pathname } = useLocation();
  const { registerPage, claimFocus } = useRouteTransition();

  useGSAP(
    (_context, contextSafe) => {
      const el = root.current;
      if (!el) return;

      const safe = <T extends (...args: never[]) => void>(fn: T): T =>
        contextSafe ? (contextSafe(fn) as T) : fn;
      // The attribute changes exactly when the phase does. Rewriting the same
      // value would still notify observers of a change that did not happen.
      const setPhase = (phase: Phase) => {
        if (el.dataset.phase !== phase) el.dataset.phase = phase;
      };
      const introTargets = Array.from(el.querySelectorAll<HTMLElement>("[data-intro]"));

      let intro: gsap.core.Timeline | null = null;
      let cancelPending: (() => void) | null = null;

      setPhase("initial");
      // Reduced motion skips the travel. A released mark means the pre-paint
      // failsafe already showed the content, and hiding it again to play an
      // intro would be worse than arriving settled.
      const instant = prefersReducedMotion() || motionReleased();
      gsap.set(introTargets, instant ? { autoAlpha: 1, y: 0 } : { autoAlpha: 0, y: INTRO_RISE });

      const settle = () => {
        intro = null;
        // Settled is CSS, not a held timeline: drop every temporary style.
        gsap.set(introTargets, { clearProps: "all" });
        setPhase("settled");
        // Only if the navigation left focus on <body>; never steal it from a
        // control the reader is using. React Router moves no focus itself.
        if (claimFocus() && document.activeElement === document.body) {
          el.focus({ preventScroll: true });
        }
      };

      // Phases advance one step at a time so anything watching the attribute
      // sees each of them, so the initial values are on the node before the
      // intro is allowed to move them, and so the intro starts after
      // <ScrollRestoration> has applied its position in the same commit.
      cancelPending = nextStep(() => {
        cancelPending = null;
        setPhase("intro");
        if (instant) {
          // No travel, but the same completion still runs.
          cancelPending = nextStep(settle);
          return;
        }
        intro = gsap
          .timeline({ defaults: { overwrite: "auto" }, onComplete: settle })
          .set(introTargets, { willChange: "transform, opacity" })
          .to(introTargets, {
            autoAlpha: 1,
            y: 0,
            duration: INTRO_DURATION,
            stagger: INTRO_STAGGER,
            ease: "power2.out",
          });
      });

      // Built here but called from the boundary's blocker effect, long after
      // this setup ran, so it goes through contextSafe to stay inside this
      // component's context and be reverted with it.
      const leave = safe((done: () => void) => {
        // An intro is not the inverse of the outro, so kill it and leave from
        // whatever is on screen rather than reversing.
        cancelPending?.();
        cancelPending = null;
        intro?.kill();
        intro = null;

        // Queried at leave time, so anything that arrived after setup — a
        // streamed region, say — leaves with the page.
        const outroTargets = Array.from(el.querySelectorAll<HTMLElement>("[data-intro]"));
        setPhase("outro");

        // Still mounted, still laid out, no longer interactive: CSS keys that
        // off the phase, so no inline style has to be cleaned up later.
        const end = () => {
          setPhase("end");
          done();
        };

        if (prefersReducedMotion()) {
          gsap.set(outroTargets, { autoAlpha: 0 });
          cancelPending = nextStep(end);
          return;
        }
        gsap
          .timeline({ defaults: { overwrite: "auto" }, onComplete: end })
          .set(outroTargets, { willChange: "transform, opacity" })
          .to(outroTargets, {
            autoAlpha: 0,
            y: -OUTRO_DRIFT,
            duration: OUTRO_DURATION,
            stagger: OUTRO_STAGGER,
            ease: "power2.in",
          });
      });

      const controller: PageController = { root: el, leave };
      const unregister = registerPage(controller);
      return () => {
        cancelPending?.();
        unregister();
      };
    },
    { scope: root, dependencies: [pathname, registerPage, claimFocus], revertOnUpdate: true },
  );

  return (
    <div ref={root} data-page data-phase="initial" tabIndex={-1} className="page-root">
      {children}
    </div>
  );
}
